@startuml actividades-diurnas
|Usuario|
start 
:Seleccioar actividades diurnas;

|Sistema|
:Direcionar para el listado de actividades diurnas;

|Usuario|
if (Hace clic en el mapa)then(si)

|Sistema|
:Redirecionar a la pagina de Google Maps;

else(no)
endif
stop
@enduml