@startuml actividades-buscar-atraciones
|Usuario|
start 
:Seleciona atraciones en el formulario;

|Sistema|
:Solicita al Backend que atracciones correponden;

|Backend|
:Devuelve la lista de atraciones;

|Sistema|
:Informa al usuario la lista de atraciones;

stop
@enduml
