@startuml actividad-creacion-tarjetas
|Usuario|
start
:Seleciona la atración;
    switch (Seleciona una atraccion)
        case ( condition A )
        :Atraccion 1;
        case ( condition B ) 
        :Atraccion 2;
        case ( condition C )
        :Atraccion 3;
        case ( condition D )
        :Atraccion 4;
        case ( condition E )
        :Atraccion 5;
    endswitch

|Sistema|
:Verifica la disponibilidad;
:Informa la disponibilidad;


|Usuario|
:Seleciona la atración;
    switch (Seleciona una atraccion)
        case ( condition A )
        :Atraccion 1;
        case ( condition B ) 
        :Atraccion 2;
        case ( condition C )
        :Atraccion 3;
        case ( condition D )
        :Atraccion 4;
        case ( condition E )
        :Atraccion 5;
    endswitch

|Usuario|
:Ingresa la cantidad de dias;
:Ingresa la cantidad de personas;
:Ingresa el email;

|Sistema|
:Guarda la nueva reserva;
:Confirma la creacion de la reserva;

stop
@enduml

