@startuml actividad-creacion-tarjetas
|Sistema|
start
:Solicita al Backend la disponibilidad;

|Backend|
:Informa la disponibilidad;

|Sistema|
:Solicita lista de atraciones;

|Sistema|
:Informa sobre nueva reserva;

|Usuario|
:Crea una reserva;
:Informa nuero de personas;
:Informa que días;

|Sistema|
:Confirma la reserva;

stop
@enduml
